package registry

// Generated by https://github.com/DynamiteMC/RegistryExtractor
var Activity = Registry{
	Default: "",
	Entries: map[string]int32{
		"minecraft:panic": 6,
		"minecraft:ram": 17,
		"minecraft:rest": 4,
		"minecraft:ride": 14,
		"minecraft:core": 0,
		"minecraft:play": 3,
		"minecraft:dig": 25,
		"minecraft:fight": 10,
		"minecraft:investigate": 22,
		"minecraft:play_dead": 15,
		"minecraft:swim": 19,
		"minecraft:idle": 1,
		"minecraft:emerge": 24,
		"minecraft:lay_spawn": 20,
		"minecraft:meet": 5,
		"minecraft:sniff": 21,
		"minecraft:admire_item": 12,
		"minecraft:avoid": 13,
		"minecraft:celebrate": 11,
		"minecraft:raid": 7,
		"minecraft:tongue": 18,
		"minecraft:work": 2,
		"minecraft:hide": 9,
		"minecraft:long_jump": 16,
		"minecraft:pre_raid": 8,
		"minecraft:roar": 23,
	},
}