package registry

// Generated by https://github.com/ZeppelinMC/RegistryExtractor
var ArmorMaterial = Registry{
	Default: "",
	Entries: map[string]int32{
		"minecraft:gold": 3,
		"minecraft:iron": 2,
		"minecraft:leather": 0,
		"minecraft:netherite": 6,
		"minecraft:turtle": 5,
		"minecraft:armadillo": 7,
		"minecraft:chainmail": 1,
		"minecraft:diamond": 4,
	},
}