package registry

// Generated by https://github.com/DynamiteMC/RegistryExtractor
var Attribute = Registry{
	Default: "",
	Entries: map[string]int32{
		"minecraft:generic.armor": 8,
		"minecraft:generic.attack_knockback": 6,
		"minecraft:generic.luck": 10,
		"minecraft:zombie.spawn_reinforcements": 11,
		"minecraft:generic.knockback_resistance": 2,
		"minecraft:generic.movement_speed": 3,
		"minecraft:generic.attack_damage": 5,
		"minecraft:generic.attack_speed": 7,
		"minecraft:horse.jump_strength": 12,
		"minecraft:generic.armor_toughness": 9,
		"minecraft:generic.flying_speed": 4,
		"minecraft:generic.follow_range": 1,
		"minecraft:generic.max_health": 0,
	},
}