package registry

// Generated by https://github.com/DynamiteMC/RegistryExtractor
var BlockPredicateType = Registry{
	Default: "",
	Entries: map[string]int32{
		"minecraft:replaceable": 5,
		"minecraft:solid": 4,
		"minecraft:all_of": 9,
		"minecraft:has_sturdy_face": 3,
		"minecraft:inside_world_bounds": 7,
		"minecraft:matching_block_tag": 1,
		"minecraft:matching_blocks": 0,
		"minecraft:matching_fluids": 2,
		"minecraft:true": 11,
		"minecraft:would_survive": 6,
		"minecraft:any_of": 8,
		"minecraft:not": 10,
	},
}