package registry

// Generated by https://github.com/DynamiteMC/RegistryExtractor
var CatVariant = Registry{
	Default: "",
	Entries: map[string]int32{
		"minecraft:all_black": 10,
		"minecraft:ragdoll": 7,
		"minecraft:white": 8,
		"minecraft:jellie": 9,
		"minecraft:persian": 6,
		"minecraft:red": 2,
		"minecraft:siamese": 3,
		"minecraft:tabby": 0,
		"minecraft:black": 1,
		"minecraft:british_shorthair": 4,
		"minecraft:calico": 5,
	},
}