package registry

// Generated by https://github.com/DynamiteMC/RegistryExtractor
var ChunkStatus = Registry{
	Default: "minecraft:empty",
	Entries: map[string]int32{
		"minecraft:empty": 0,
		"minecraft:features": 7,
		"minecraft:initialize_light": 8,
		"minecraft:light": 9,
		"minecraft:noise": 4,
		"minecraft:structure_references": 2,
		"minecraft:biomes": 3,
		"minecraft:carvers": 6,
		"minecraft:full": 11,
		"minecraft:spawn": 10,
		"minecraft:structure_starts": 1,
		"minecraft:surface": 5,
	},
}