package registry

// Generated by https://github.com/ZeppelinMC/RegistryExtractor
var CreativeModeTab = Registry{
	Default: "",
	Entries: map[string]int32{
		"minecraft:natural_blocks": 2,
		"minecraft:redstone_blocks": 4,
		"minecraft:tools_and_utilities": 7,
		"minecraft:building_blocks": 0,
		"minecraft:hotbar": 5,
		"minecraft:ingredients": 10,
		"minecraft:inventory": 13,
		"minecraft:colored_blocks": 1,
		"minecraft:combat": 8,
		"minecraft:functional_blocks": 3,
		"minecraft:op_blocks": 12,
		"minecraft:food_and_drinks": 9,
		"minecraft:search": 6,
		"minecraft:spawn_eggs": 11,
	},
}