package registry

// Generated by https://github.com/ZeppelinMC/RegistryExtractor
var DecoratedPotPattern = Registry{
	Default: "",
	Entries: map[string]int32{
		"minecraft:heart": 11,
		"minecraft:sheaf": 19,
		"minecraft:archer": 1,
		"minecraft:brewer": 4,
		"minecraft:explorer": 7,
		"minecraft:friend": 9,
		"minecraft:guster": 10,
		"minecraft:shelter": 20,
		"minecraft:danger": 6,
		"minecraft:heartbreak": 12,
		"minecraft:miner": 14,
		"minecraft:prize": 17,
		"minecraft:scrape": 18,
		"minecraft:howl": 13,
		"minecraft:mourner": 15,
		"minecraft:plenty": 16,
		"minecraft:arms_up": 2,
		"minecraft:blade": 3,
		"minecraft:blank": 23,
		"minecraft:burn": 5,
		"minecraft:flow": 8,
		"minecraft:angler": 0,
		"minecraft:skull": 21,
		"minecraft:snort": 22,
	},
}