package registry

// Generated by https://github.com/DynamiteMC/RegistryExtractor
var DecoratedPotPatterns = Registry{
	Default: "",
	Entries: map[string]int32{
		"minecraft:howl_pottery_pattern": 12,
		"minecraft:brewer_pottery_pattern": 5,
		"minecraft:burn_pottery_pattern": 6,
		"minecraft:danger_pottery_pattern": 7,
		"minecraft:heartbreak_pottery_pattern": 11,
		"minecraft:plenty_pottery_pattern": 15,
		"minecraft:prize_pottery_pattern": 16,
		"minecraft:blade_pottery_pattern": 4,
		"minecraft:friend_pottery_pattern": 9,
		"minecraft:miner_pottery_pattern": 13,
		"minecraft:mourner_pottery_pattern": 14,
		"minecraft:snort_pottery_pattern": 20,
		"minecraft:angler_pottery_pattern": 1,
		"minecraft:explorer_pottery_pattern": 8,
		"minecraft:sheaf_pottery_pattern": 17,
		"minecraft:skull_pottery_pattern": 19,
		"minecraft:heart_pottery_pattern": 10,
		"minecraft:shelter_pottery_pattern": 18,
		"minecraft:archer_pottery_pattern": 2,
		"minecraft:arms_up_pottery_pattern": 3,
		"minecraft:decorated_pot_base": 21,
		"minecraft:decorated_pot_side": 0,
	},
}