package registry

// Generated by https://github.com/ZeppelinMC/RegistryExtractor
var EnchantmentLevelBasedValueType = Registry{
	Default: "",
	Entries: map[string]int32{
		"minecraft:clamped": 0,
		"minecraft:fraction": 1,
		"minecraft:levels_squared": 2,
		"minecraft:linear": 3,
		"minecraft:lookup": 4,
	},
}