package registry

// Generated by https://github.com/ZeppelinMC/RegistryExtractor
var EnchantmentLocationBasedEffectType = Registry{
	Default: "",
	Entries: map[string]int32{
		"minecraft:play_sound": 7,
		"minecraft:summon_entity": 13,
		"minecraft:all_of": 0,
		"minecraft:damage_item": 4,
		"minecraft:replace_block": 8,
		"minecraft:run_function": 10,
		"minecraft:attribute": 2,
		"minecraft:ignite": 6,
		"minecraft:replace_disk": 9,
		"minecraft:spawn_particles": 12,
		"minecraft:apply_mob_effect": 1,
		"minecraft:damage_entity": 3,
		"minecraft:explode": 5,
		"minecraft:set_block_properties": 11,
	},
}