package registry

// Generated by https://github.com/ZeppelinMC/RegistryExtractor
var EnchantmentProviderType = Registry{
	Default: "",
	Entries: map[string]int32{
		"minecraft:by_cost": 0,
		"minecraft:by_cost_with_difficulty": 1,
		"minecraft:single": 2,
	},
}