package registry

// Generated by https://github.com/ZeppelinMC/RegistryExtractor
var EnchantmentEntityEffectType = Registry{
	Default: "",
	Entries: map[string]int32{
		"minecraft:spawn_particles": 11,
		"minecraft:summon_entity": 12,
		"minecraft:all_of": 0,
		"minecraft:damage_entity": 2,
		"minecraft:explode": 4,
		"minecraft:play_sound": 6,
		"minecraft:replace_block": 7,
		"minecraft:replace_disk": 8,
		"minecraft:apply_mob_effect": 1,
		"minecraft:damage_item": 3,
		"minecraft:ignite": 5,
		"minecraft:run_function": 9,
		"minecraft:set_block_properties": 10,
	},
}