package registry

// Generated by https://github.com/ZeppelinMC/RegistryExtractor
var EnchantmentValueEffectType = Registry{
	Default: "",
	Entries: map[string]int32{
		"minecraft:remove_binomial": 3,
		"minecraft:set": 4,
		"minecraft:add": 0,
		"minecraft:all_of": 1,
		"minecraft:multiply": 2,
	},
}