package registry

// Generated by https://github.com/ZeppelinMC/RegistryExtractor
var EntitySubPredicateType = Registry{
	Default: "",
	Entries: map[string]int32{
		"minecraft:parrot": 13,
		"minecraft:rabbit": 9,
		"minecraft:wolf": 18,
		"minecraft:axolotl": 5,
		"minecraft:fox": 7,
		"minecraft:mooshroom": 8,
		"minecraft:painting": 15,
		"minecraft:player": 2,
		"minecraft:raider": 4,
		"minecraft:boat": 6,
		"minecraft:horse": 10,
		"minecraft:llama": 11,
		"minecraft:slime": 3,
		"minecraft:cat": 16,
		"minecraft:fishing_hook": 1,
		"minecraft:frog": 17,
		"minecraft:lightning": 0,
		"minecraft:tropical_fish": 14,
		"minecraft:villager": 12,
	},
}