package registry

// Generated by https://github.com/DynamiteMC/RegistryExtractor
var FloatProviderType = Registry{
	Default: "",
	Entries: map[string]int32{
		"minecraft:trapezoid": 3,
		"minecraft:uniform": 1,
		"minecraft:clamped_normal": 2,
		"minecraft:constant": 0,
	},
}