package registry

// Generated by https://github.com/DynamiteMC/RegistryExtractor
var Fluid = Registry{
	Default: "minecraft:empty",
	Entries: map[string]int32{
		"minecraft:flowing_water": 1,
		"minecraft:lava": 4,
		"minecraft:water": 2,
		"minecraft:empty": 0,
		"minecraft:flowing_lava": 3,
	},
}