package registry

// Generated by https://github.com/DynamiteMC/RegistryExtractor
var FrogVariant = Registry{
	Default: "",
	Entries: map[string]int32{
		"minecraft:cold": 2,
		"minecraft:temperate": 0,
		"minecraft:warm": 1,
	},
}