package registry

// Generated by https://github.com/ZeppelinMC/RegistryExtractor
var HeightProviderType = Registry{
	Default: "",
	Entries: map[string]int32{
		"minecraft:biased_to_bottom": 2,
		"minecraft:constant": 0,
		"minecraft:trapezoid": 4,
		"minecraft:uniform": 1,
		"minecraft:very_biased_to_bottom": 3,
		"minecraft:weighted_list": 5,
	},
}