package registry

// Generated by https://github.com/ZeppelinMC/RegistryExtractor
var Instrument = Registry{
	Default: "",
	Entries: map[string]int32{
		"minecraft:sing_goat_horn": 1,
		"minecraft:yearn_goat_horn": 6,
		"minecraft:admire_goat_horn": 4,
		"minecraft:call_goat_horn": 5,
		"minecraft:dream_goat_horn": 7,
		"minecraft:feel_goat_horn": 3,
		"minecraft:ponder_goat_horn": 0,
		"minecraft:seek_goat_horn": 2,
	},
}