package registry

// Generated by https://github.com/ZeppelinMC/RegistryExtractor
var IntProviderType = Registry{
	Default: "",
	Entries: map[string]int32{
		"minecraft:weighted_list": 4,
		"minecraft:biased_to_bottom": 2,
		"minecraft:clamped": 3,
		"minecraft:clamped_normal": 5,
		"minecraft:constant": 0,
		"minecraft:uniform": 1,
	},
}