package registry

// Generated by https://github.com/ZeppelinMC/RegistryExtractor
var ItemSubPredicateType = Registry{
	Default: "",
	Entries: map[string]int32{
		"minecraft:potion_contents": 3,
		"minecraft:stored_enchantments": 2,
		"minecraft:trim": 12,
		"minecraft:written_book_content": 10,
		"minecraft:container": 5,
		"minecraft:firework_explosion": 7,
		"minecraft:fireworks": 8,
		"minecraft:bundle_contents": 6,
		"minecraft:enchantments": 1,
		"minecraft:writable_book_content": 9,
		"minecraft:attribute_modifiers": 11,
		"minecraft:custom_data": 4,
		"minecraft:jukebox_playable": 13,
		"minecraft:damage": 0,
	},
}