package registry

// Generated by https://github.com/DynamiteMC/RegistryExtractor
var LootFunctionType = Registry{
	Default: "",
	Entries: map[string]int32{
		"minecraft:limit_count": 14,
		"minecraft:set_attributes": 8,
		"minecraft:set_contents": 13,
		"minecraft:set_nbt": 4,
		"minecraft:set_potion": 23,
		"minecraft:set_stew_effect": 11,
		"minecraft:apply_bonus": 15,
		"minecraft:furnace_smelt": 5,
		"minecraft:set_name": 9,
		"minecraft:enchant_with_levels": 1,
		"minecraft:looting_enchant": 6,
		"minecraft:reference": 25,
		"minecraft:set_count": 0,
		"minecraft:set_damage": 7,
		"minecraft:fill_player_head": 19,
		"minecraft:set_enchantments": 3,
		"minecraft:set_lore": 18,
		"minecraft:exploration_map": 10,
		"minecraft:set_banner_pattern": 22,
		"minecraft:set_instrument": 24,
		"minecraft:copy_nbt": 20,
		"minecraft:copy_state": 21,
		"minecraft:enchant_randomly": 2,
		"minecraft:explosion_decay": 17,
		"minecraft:set_loot_table": 16,
		"minecraft:copy_name": 12,
	},
}