package registry

// Generated by https://github.com/ZeppelinMC/RegistryExtractor
var LootScoreProviderType = Registry{
	Default: "",
	Entries: map[string]int32{
		"minecraft:context": 1,
		"minecraft:fixed": 0,
	},
}