package registry

// Generated by https://github.com/ZeppelinMC/RegistryExtractor
var LootPoolEntryType = Registry{
	Default: "",
	Entries: map[string]int32{
		"minecraft:group": 7,
		"minecraft:item": 1,
		"minecraft:loot_table": 2,
		"minecraft:sequence": 6,
		"minecraft:tag": 4,
		"minecraft:alternatives": 5,
		"minecraft:dynamic": 3,
		"minecraft:empty": 0,
	},
}