package registry

// Generated by https://github.com/ZeppelinMC/RegistryExtractor
var LootConditionType = Registry{
	Default: "",
	Entries: map[string]int32{
		"minecraft:all_of": 2,
		"minecraft:block_state_property": 8,
		"minecraft:entity_properties": 5,
		"minecraft:table_bonus": 10,
		"minecraft:time_check": 16,
		"minecraft:value_check": 17,
		"minecraft:weather_check": 14,
		"minecraft:enchantment_active_check": 18,
		"minecraft:killed_by_player": 6,
		"minecraft:match_tool": 9,
		"minecraft:random_chance": 3,
		"minecraft:survives_explosion": 11,
		"minecraft:any_of": 1,
		"minecraft:location_check": 13,
		"minecraft:reference": 15,
		"minecraft:damage_source_properties": 12,
		"minecraft:entity_scores": 7,
		"minecraft:inverted": 0,
		"minecraft:random_chance_with_enchanted_bonus": 4,
	},
}