package registry

// Generated by https://github.com/DynamiteMC/RegistryExtractor
var LootNbtProviderType = Registry{
	Default: "",
	Entries: map[string]int32{
		"minecraft:context": 1,
		"minecraft:storage": 0,
	},
}