package registry

// Generated by https://github.com/DynamiteMC/RegistryExtractor
var LootNumberProviderType = Registry{
	Default: "",
	Entries: map[string]int32{
		"minecraft:binomial": 2,
		"minecraft:constant": 0,
		"minecraft:score": 3,
		"minecraft:uniform": 1,
	},
}