package registry

// Generated by https://github.com/ZeppelinMC/RegistryExtractor
var LootNumberProviderType = Registry{
	Default: "",
	Entries: map[string]int32{
		"minecraft:binomial": 2,
		"minecraft:constant": 0,
		"minecraft:enchantment_level": 5,
		"minecraft:score": 3,
		"minecraft:storage": 4,
		"minecraft:uniform": 1,
	},
}