package registry

// Generated by https://github.com/ZeppelinMC/RegistryExtractor
var Menu = Registry{
	Default: "",
	Entries: map[string]int32{
		"minecraft:smoker": 22,
		"minecraft:crafter_3x3": 7,
		"minecraft:generic_9x1": 0,
		"minecraft:generic_9x3": 2,
		"minecraft:generic_9x5": 4,
		"minecraft:generic_9x6": 5,
		"minecraft:shulker_box": 20,
		"minecraft:stonecutter": 24,
		"minecraft:beacon": 9,
		"minecraft:crafting": 12,
		"minecraft:furnace": 14,
		"minecraft:generic_9x2": 1,
		"minecraft:generic_9x4": 3,
		"minecraft:grindstone": 15,
		"minecraft:cartography_table": 23,
		"minecraft:enchantment": 13,
		"minecraft:hopper": 16,
		"minecraft:lectern": 17,
		"minecraft:smithing": 21,
		"minecraft:anvil": 8,
		"minecraft:blast_furnace": 10,
		"minecraft:brewing_stand": 11,
		"minecraft:generic_3x3": 6,
		"minecraft:loom": 18,
		"minecraft:merchant": 19,
	},
}