package registry

// Generated by https://github.com/DynamiteMC/RegistryExtractor
var Menu = Registry{
	Default: "",
	Entries: map[string]int32{
		"minecraft:brewing_stand": 10,
		"minecraft:enchantment": 12,
		"minecraft:generic_9x3": 2,
		"minecraft:merchant": 18,
		"minecraft:anvil": 7,
		"minecraft:generic_9x5": 4,
		"minecraft:generic_9x6": 5,
		"minecraft:hopper": 15,
		"minecraft:loom": 17,
		"minecraft:smoker": 21,
		"minecraft:beacon": 8,
		"minecraft:crafting": 11,
		"minecraft:generic_9x2": 1,
		"minecraft:grindstone": 14,
		"minecraft:lectern": 16,
		"minecraft:shulker_box": 19,
		"minecraft:smithing": 20,
		"minecraft:stonecutter": 23,
		"minecraft:blast_furnace": 9,
		"minecraft:cartography_table": 22,
		"minecraft:furnace": 13,
		"minecraft:generic_3x3": 6,
		"minecraft:generic_9x1": 0,
		"minecraft:generic_9x4": 3,
	},
}