package registry

// Generated by https://github.com/ZeppelinMC/RegistryExtractor
var NumberFormatType = Registry{
	Default: "",
	Entries: map[string]int32{
		"minecraft:blank": 0,
		"minecraft:fixed": 2,
		"minecraft:styled": 1,
	},
}