package registry

// Generated by https://github.com/ZeppelinMC/RegistryExtractor
var PointOfInterestType = Registry{
	Default: "",
	Entries: map[string]int32{
		"minecraft:weaponsmith": 12,
		"minecraft:armorer": 0,
		"minecraft:bee_nest": 16,
		"minecraft:cartographer": 2,
		"minecraft:fisherman": 5,
		"minecraft:leatherworker": 7,
		"minecraft:shepherd": 10,
		"minecraft:beehive": 15,
		"minecraft:fletcher": 6,
		"minecraft:librarian": 8,
		"minecraft:lightning_rod": 19,
		"minecraft:nether_portal": 17,
		"minecraft:butcher": 1,
		"minecraft:cleric": 3,
		"minecraft:lodestone": 18,
		"minecraft:meeting": 14,
		"minecraft:toolsmith": 11,
		"minecraft:farmer": 4,
		"minecraft:home": 13,
		"minecraft:mason": 9,
	},
}