package registry

// Generated by https://github.com/DynamiteMC/RegistryExtractor
var PosRuleTest = Registry{
	Default: "",
	Entries: map[string]int32{
		"minecraft:always_true": 0,
		"minecraft:axis_aligned_linear_pos": 2,
		"minecraft:linear_pos": 1,
	},
}