package registry

// Generated by https://github.com/DynamiteMC/RegistryExtractor
var PositionSourceType = Registry{
	Default: "",
	Entries: map[string]int32{
		"minecraft:block": 0,
		"minecraft:entity": 1,
	},
}