package registry

// Generated by https://github.com/ZeppelinMC/RegistryExtractor
var RecipeType = Registry{
	Default: "",
	Entries: map[string]int32{
		"minecraft:campfire_cooking": 4,
		"minecraft:crafting": 0,
		"minecraft:smelting": 1,
		"minecraft:smithing": 6,
		"minecraft:smoking": 3,
		"minecraft:stonecutting": 5,
		"minecraft:blasting": 2,
	},
}