package registry

// Generated by https://github.com/ZeppelinMC/RegistryExtractor
var RecipeSerializer = Registry{
	Default: "",
	Entries: map[string]int32{
		"minecraft:campfire_cooking": 18,
		"minecraft:crafting_special_bannerduplicate": 10,
		"minecraft:crafting_special_firework_star": 7,
		"minecraft:crafting_special_mapextending": 5,
		"minecraft:crafting_special_tippedarrow": 9,
		"minecraft:smithing_transform": 20,
		"minecraft:stonecutting": 19,
		"minecraft:crafting_shapeless": 1,
		"minecraft:crafting_special_firework_rocket": 6,
		"minecraft:crafting_special_shielddecoration": 11,
		"minecraft:crafting_special_shulkerboxcoloring": 12,
		"minecraft:crafting_special_suspiciousstew": 13,
		"minecraft:smithing_trim": 21,
		"minecraft:crafting_special_mapcloning": 4,
		"minecraft:crafting_special_repairitem": 14,
		"minecraft:blasting": 16,
		"minecraft:crafting_decorated_pot": 22,
		"minecraft:crafting_shaped": 0,
		"minecraft:crafting_special_armordye": 2,
		"minecraft:crafting_special_bookcloning": 3,
		"minecraft:crafting_special_firework_star_fade": 8,
		"minecraft:smelting": 15,
		"minecraft:smoking": 17,
	},
}