package registry

// Generated by https://github.com/ZeppelinMC/RegistryExtractor

type Registry struct {
	Default string
	Entries map[string]int32
}

func (r Registry) Get(n string) (int32, bool) {
	i, ok := r.Entries[n]
	if !ok {
		if r.Default != "" {
			i, ok = r.Entries[r.Default]
		}
	}
	return i, ok
}

func (r Registry) Find(id int32) (string, bool) {
	for n, e := range r.Entries {
		if e == id {
			return n, true
		}
	}
	return "", false
}