package registry

// This package contains registries that are not sent to the client, meaning the ids are constants

// Generated by https://github.com/ZeppelinMC/RegistryExtractor

type Registry struct {
	Default string
	Entries map[string]int32
}

// Looks up the name in the registry and returns the protocol id if found, otherwise default or 0
func (r Registry) Get(n string) int32 {
	i, _ := r.Lookup(n)

	return i
}

// Looks up the name in the registry and returns the protocol id. If the protocol id is not found, returns the default entry and(ok=false), and if that is not found either then returns 0
func (r Registry) Lookup(n string) (int32, bool) {
	i, ok := r.Entries[n]
	if !ok {
		if r.Default != "" {
			i = r.Entries[r.Default]
		}
	}
	return i, ok
}

// Returns the name of the protocol id
func (r Registry) NameOf(id int32) (string, bool) {
	for n, e := range r.Entries {
		if e == id {
			return n, true
		}
	}
	return "", false
}
