package registry

// Generated by https://github.com/DynamiteMC/RegistryExtractor
var RuleTest = Registry{
	Default: "",
	Entries: map[string]int32{
		"minecraft:blockstate_match": 2,
		"minecraft:random_block_match": 4,
		"minecraft:random_blockstate_match": 5,
		"minecraft:tag_match": 3,
		"minecraft:always_true": 0,
		"minecraft:block_match": 1,
	},
}