package registry

// Generated by https://github.com/ZeppelinMC/RegistryExtractor
var RuleBlockEntityModifier = Registry{
	Default: "",
	Entries: map[string]int32{
		"minecraft:append_loot": 3,
		"minecraft:append_static": 2,
		"minecraft:clear": 0,
		"minecraft:passthrough": 1,
	},
}