package registry

// Generated by https://github.com/DynamiteMC/RegistryExtractor
var Schedule = Registry{
	Default: "",
	Entries: map[string]int32{
		"minecraft:empty": 0,
		"minecraft:simple": 1,
		"minecraft:villager_baby": 2,
		"minecraft:villager_default": 3,
	},
}