package registry

// Generated by https://github.com/ZeppelinMC/RegistryExtractor
var SensorType = Registry{
	Default: "minecraft:dummy",
	Entries: map[string]int32{
		"minecraft:armadillo_scare_detected": 10,
		"minecraft:breeze_attack_entity_sensor": 25,
		"minecraft:frog_temptations": 18,
		"minecraft:hurt_by": 5,
		"minecraft:nearest_adult": 14,
		"minecraft:sniffer_temptations": 24,
		"minecraft:villager_hostiles": 6,
		"minecraft:piglin_brute_specific_sensor": 12,
		"minecraft:axolotl_attackables": 15,
		"minecraft:axolotl_temptations": 16,
		"minecraft:camel_temptations": 19,
		"minecraft:dummy": 0,
		"minecraft:golem_detected": 9,
		"minecraft:nearest_bed": 4,
		"minecraft:nearest_items": 1,
		"minecraft:secondary_pois": 8,
		"minecraft:villager_babies": 7,
		"minecraft:warden_entity_sensor": 23,
		"minecraft:goat_temptations": 17,
		"minecraft:hoglin_specific_sensor": 13,
		"minecraft:nearest_players": 3,
		"minecraft:piglin_specific_sensor": 11,
		"minecraft:armadillo_temptations": 20,
		"minecraft:frog_attackables": 21,
		"minecraft:is_in_water": 22,
		"minecraft:nearest_living_entities": 2,
	},
}