package registry

// Generated by https://github.com/ZeppelinMC/RegistryExtractor
var StatType = Registry{
	Default: "",
	Entries: map[string]int32{
		"minecraft:used": 2,
		"minecraft:broken": 3,
		"minecraft:killed_by": 7,
		"minecraft:picked_up": 4,
		"minecraft:killed": 6,
		"minecraft:mined": 0,
		"minecraft:crafted": 1,
		"minecraft:custom": 8,
		"minecraft:dropped": 5,
	},
}