package registry

// Generated by https://github.com/DynamiteMC/RegistryExtractor
var VillagerProfession = Registry{
	Default: "minecraft:none",
	Entries: map[string]int32{
		"minecraft:butcher": 2,
		"minecraft:librarian": 9,
		"minecraft:mason": 10,
		"minecraft:toolsmith": 13,
		"minecraft:armorer": 1,
		"minecraft:cleric": 4,
		"minecraft:nitwit": 11,
		"minecraft:shepherd": 12,
		"minecraft:weaponsmith": 14,
		"minecraft:cartographer": 3,
		"minecraft:farmer": 5,
		"minecraft:leatherworker": 8,
		"minecraft:fisherman": 6,
		"minecraft:fletcher": 7,
		"minecraft:none": 0,
	},
}