package registry

// Generated by https://github.com/DynamiteMC/RegistryExtractor
var VillagerType = Registry{
	Default: "minecraft:plains",
	Entries: map[string]int32{
		"minecraft:desert": 0,
		"minecraft:jungle": 1,
		"minecraft:plains": 2,
		"minecraft:savanna": 3,
		"minecraft:snow": 4,
		"minecraft:swamp": 5,
		"minecraft:taiga": 6,
	},
}