package registry

// Generated by https://github.com/ZeppelinMC/RegistryExtractor
var WorldgenTrunkPlacerType = Registry{
	Default: "",
	Entries: map[string]int32{
		"minecraft:dark_oak_trunk_placer": 4,
		"minecraft:forking_trunk_placer": 1,
		"minecraft:mega_jungle_trunk_placer": 3,
		"minecraft:upwards_branching_trunk_placer": 7,
		"minecraft:bending_trunk_placer": 6,
		"minecraft:cherry_trunk_placer": 8,
		"minecraft:fancy_trunk_placer": 5,
		"minecraft:giant_trunk_placer": 2,
		"minecraft:straight_trunk_placer": 0,
	},
}