package registry

// Generated by https://github.com/ZeppelinMC/RegistryExtractor
var WorldgenBlockStateProviderType = Registry{
	Default: "",
	Entries: map[string]int32{
		"minecraft:noise_threshold_provider": 2,
		"minecraft:randomized_int_state_provider": 6,
		"minecraft:rotated_block_provider": 5,
		"minecraft:simple_state_provider": 0,
		"minecraft:weighted_state_provider": 1,
		"minecraft:dual_noise_provider": 4,
		"minecraft:noise_provider": 3,
	},
}