package registry

// Generated by https://github.com/ZeppelinMC/RegistryExtractor
var WorldgenPoolAliasBinding = Registry{
	Default: "",
	Entries: map[string]int32{
		"minecraft:direct": 2,
		"minecraft:random": 0,
		"minecraft:random_group": 1,
	},
}