package registry

// Generated by https://github.com/ZeppelinMC/RegistryExtractor
var WorldgenBiomeSource = Registry{
	Default: "",
	Entries: map[string]int32{
		"minecraft:checkerboard": 2,
		"minecraft:fixed": 0,
		"minecraft:multi_noise": 1,
		"minecraft:the_end": 3,
	},
}