package registry

// Generated by https://github.com/ZeppelinMC/RegistryExtractor
var WorldgenCarver = Registry{
	Default: "",
	Entries: map[string]int32{
		"minecraft:cave": 0,
		"minecraft:nether_cave": 1,
		"minecraft:canyon": 2,
	},
}