package registry

// Generated by https://github.com/DynamiteMC/RegistryExtractor
var WorldgenFoliagePlacerType = Registry{
	Default: "",
	Entries: map[string]int32{
		"minecraft:acacia_foliage_placer": 3,
		"minecraft:jungle_foliage_placer": 6,
		"minecraft:mega_pine_foliage_placer": 7,
		"minecraft:pine_foliage_placer": 2,
		"minecraft:spruce_foliage_placer": 1,
		"minecraft:blob_foliage_placer": 0,
		"minecraft:bush_foliage_placer": 4,
		"minecraft:cherry_foliage_placer": 10,
		"minecraft:dark_oak_foliage_placer": 8,
		"minecraft:fancy_foliage_placer": 5,
		"minecraft:random_spread_foliage_placer": 9,
	},
}