package registry

// Generated by https://github.com/DynamiteMC/RegistryExtractor
var WorldgenStructureProcessor = Registry{
	Default: "",
	Entries: map[string]int32{
		"minecraft:block_rot": 1,
		"minecraft:gravity": 2,
		"minecraft:jigsaw_replacement": 3,
		"minecraft:nop": 5,
		"minecraft:lava_submerged_block": 8,
		"minecraft:protected_blocks": 9,
		"minecraft:rule": 4,
		"minecraft:blackstone_replace": 7,
		"minecraft:block_age": 6,
		"minecraft:block_ignore": 0,
		"minecraft:capped": 10,
	},
}