package registry

// Generated by https://github.com/ZeppelinMC/RegistryExtractor
var WorldgenPlacementModifierType = Registry{
	Default: "",
	Entries: map[string]int32{
		"minecraft:rarity_filter": 1,
		"minecraft:surface_water_depth_filter": 3,
		"minecraft:block_predicate_filter": 0,
		"minecraft:carving_mask": 14,
		"minecraft:heightmap": 10,
		"minecraft:noise_based_count": 6,
		"minecraft:noise_threshold_count": 7,
		"minecraft:biome": 4,
		"minecraft:in_square": 12,
		"minecraft:random_offset": 13,
		"minecraft:surface_relative_threshold_filter": 2,
		"minecraft:count": 5,
		"minecraft:count_on_every_layer": 8,
		"minecraft:environment_scan": 9,
		"minecraft:fixed_placement": 15,
		"minecraft:height_range": 11,
	},
}