package registry

// Generated by https://github.com/ZeppelinMC/RegistryExtractor
var WorldgenRootPlacerType = Registry{
	Default: "",
	Entries: map[string]int32{
		"minecraft:mangrove_root_placer": 0,
	},
}