package registry

// Generated by https://github.com/ZeppelinMC/RegistryExtractor
var WorldgenTreeDecoratorType = Registry{
	Default: "",
	Entries: map[string]int32{
		"minecraft:leave_vine": 1,
		"minecraft:trunk_vine": 0,
		"minecraft:alter_ground": 4,
		"minecraft:attached_to_leaves": 5,
		"minecraft:beehive": 3,
		"minecraft:cocoa": 2,
	},
}