package registry

// Generated by https://github.com/ZeppelinMC/RegistryExtractor
var WorldgenChunkGenerator = Registry{
	Default: "",
	Entries: map[string]int32{
		"minecraft:debug": 2,
		"minecraft:flat": 1,
		"minecraft:noise": 0,
	},
}