package registry

// Generated by https://github.com/ZeppelinMC/RegistryExtractor
var WorldgenFeatureSizeType = Registry{
	Default: "",
	Entries: map[string]int32{
		"minecraft:three_layers_feature_size": 1,
		"minecraft:two_layers_feature_size": 0,
	},
}