package registry

// Generated by https://github.com/ZeppelinMC/RegistryExtractor
var WorldgenStructurePlacement = Registry{
	Default: "",
	Entries: map[string]int32{
		"minecraft:concentric_rings": 1,
		"minecraft:random_spread": 0,
	},
}