package registry

// Generated by https://github.com/ZeppelinMC/RegistryExtractor
var WorldgenMaterialCondition = Registry{
	Default: "",
	Entries: map[string]int32{
		"minecraft:steep": 6,
		"minecraft:stone_depth": 10,
		"minecraft:temperature": 5,
		"minecraft:vertical_gradient": 2,
		"minecraft:y_above": 3,
		"minecraft:above_preliminary_surface": 9,
		"minecraft:biome": 0,
		"minecraft:hole": 8,
		"minecraft:noise_threshold": 1,
		"minecraft:not": 7,
		"minecraft:water": 4,
	},
}