package registry

// Generated by https://github.com/DynamiteMC/RegistryExtractor
var WorldgenStructurePoolElement = Registry{
	Default: "",
	Entries: map[string]int32{
		"minecraft:empty_pool_element": 3,
		"minecraft:feature_pool_element": 2,
		"minecraft:legacy_single_pool_element": 4,
		"minecraft:list_pool_element": 1,
		"minecraft:single_pool_element": 0,
	},
}