package registry

// Generated by https://github.com/DynamiteMC/RegistryExtractor
var WorldgenStructureType = Registry{
	Default: "",
	Entries: map[string]int32{
		"minecraft:desert_pyramid": 1,
		"minecraft:fortress": 3,
		"minecraft:jigsaw": 5,
		"minecraft:shipwreck": 12,
		"minecraft:buried_treasure": 0,
		"minecraft:igloo": 4,
		"minecraft:mineshaft": 7,
		"minecraft:swamp_hut": 14,
		"minecraft:woodland_mansion": 15,
		"minecraft:end_city": 2,
		"minecraft:nether_fossil": 8,
		"minecraft:ocean_ruin": 10,
		"minecraft:jungle_temple": 6,
		"minecraft:ocean_monument": 9,
		"minecraft:ruined_portal": 11,
		"minecraft:stronghold": 13,
	},
}