package registry

// Generated by https://github.com/DynamiteMC/RegistryExtractor
var WorldgenMaterialRule = Registry{
	Default: "",
	Entries: map[string]int32{
		"minecraft:bandlands": 0,
		"minecraft:block": 1,
		"minecraft:condition": 3,
		"minecraft:sequence": 2,
	},
}