package enum

const (
	BiomeBadlands int32 = iota
	BiomeBambooJungle
	BiomeBasaltDeltas
	BiomeBeach
	BiomeBirchForest
	BiomeCherryGrove
	BiomeColdOcean
	BiomeCrimsonForest
	BiomeDarkForest
	BiomeDeepColdOcean
	BiomeDeepDark
	BiomeDeepFrozenOcean
	BiomeDeepLukewarmOcean
	BiomeDeepOcean
	BiomeDesert
	BiomeDripstoneCaves
	BiomeEndBarrens
	BiomeEndHighlands
	BiomeEndMidlands
	BiomeErodedBadlands
	BiomeFlowerForest
	BiomeForest
	BiomeFrozenOcean
	BiomeFrozenPeaks
	BiomeFrozenRiver
	BiomeGrove
	BiomeIceSpikes
	BiomeJaggedPeaks
	BiomeJungle
	BiomeLukewarmOcean
	BiomeLushCaves
	BiomeMangroveSwamp
	BiomeMeadow
	BiomeMushroomFields
	BiomeNetherWastes
	BiomeOcean
	BiomeOldGrowthBirchForest
	BiomeOldGrowthPineTaiga
	BiomeOldGrowthSpruceForest
	BiomePlains
	BiomeRiver
	BiomeSavanna
	BiomeSavannaPlateau
	BiomeSmallEndIslands
	BiomeSnowyBeach
	BiomeSnowyPlains
	BiomeSnowySlopes
	BiomeSnowyTaiga
	BiomeSoulSandValley
	BiomeSparseJungle
	BiomeStonyPeaks
	BiomeStonyShore
	BiomeSunflowerPlains
	BiomeSwamp
	BiomeTaiga
	BiomeTheEnd
	BiomeTheVoid
	BiomeWarmOcean
	BiomeWarpedForest
	BiomeWindsweptForest
	BiomeWindsweptGravellyHills
	BiomeWindsweptHills
	BiomeWindsweptSavanna
	BiomeWoodedBadlands
)
